import Vue from 'vue'

import { Button, NavBar, Tabbar, TabbarItem, Icon, Swipe, SwipeItem, Grid, GridItem, Tab, Tabs, Sticky,
    RadioGroup, Radio, Checkbox, CheckboxGroup, Stepper, Sidebar, SidebarItem, cell, Form, Field, Toast,
    Empty, ActionSheet, ImagePreview, Uploader, Dialog, AddressList, AddressEdit, Area, GoodsAction,
    GoodsActionIcon, GoodsActionButton, Sku, SubmitBar, ShareSheet, Divider, CellGroup } from "vant";
Vue.use(Button)
    .use(NavBar)
    .use(Tabbar)
    .use(TabbarItem)
    .use(Icon)
    .use(Swipe)
    .use(SwipeItem)
    .use(Grid)
    .use(GridItem)
    .use(Tab)
    .use(Tabs)
    .use(Sticky)
    .use(RadioGroup)
    .use(Radio)
    .use(Checkbox)
    .use(CheckboxGroup)
    .use(Stepper)
    .use(Sidebar)
    .use(SidebarItem)
    .use(cell)
    .use(Form)
    .use(Field)
    .use(Toast)
    .use(Empty)
    .use(ActionSheet)
    .use(ImagePreview)
    .use(Uploader)
    .use(Dialog)
    .use(AddressList)
    .use(AddressEdit)
    .use(Area)
    .use(GoodsAction)
    .use(GoodsActionIcon)
    .use(GoodsActionButton)
    .use(Sku)
    .use(SubmitBar)
    .use(ShareSheet)
    .use(Divider)
    .use(CellGroup)